packages:
  - '.'

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  '@whiskeysockets/baileys': true
  bcrypt: true
  prisma: true
  protobufjs: true
  sharp: true
