ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "totalGaiolas" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "mensagemPetPronto" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "avisoTrial3dEnviadoEm" TIMESTAMP(3);
